검토 요청
qnbz209/pogomgom-react pull request #2
Opened 2020-12-01 12:04 UTC by qnbz209

props와 state가 update되는 데에 delay가 발생합니다

2020-12-02 06:36 UTC, ryuina requested changes

2020-12-02 06:36 UTC, ryuina commented on src/components/IDLabel.jsx
> +                {this.renderErrmsg}
이 부분은 `renderErrmsg` 함수의 실행결과가 {} q부분을 대치해야 하기 때문에 함수 이름뿐 아닌 실행 명령까지 내려주어야합니다.
`{this.renderErrmsg}` -> 함수 그 자체
`{this.renderErrmsg()}` -> 함수의 실행 결과

2020-12-02 06:36 UTC, ryuina commented on src/components/IDLabel.jsx
> +                {this.renderErrmsg}
그리고 55번째 줄을 `{this.renderErrmsg()}`로 변경하면 label밑에 `<p></p>` tag가 추가로 생깁니다. 
에러메세지가 필요없을때는 <p> tag가 화면에 보이지 않도록 해주세요~

2020-12-02 06:36 UTC, ryuina commented on src/components/IDLabel.jsx
> +        this.props.handleID(event.target.value);
`validateID`는 어떤걸 validation하는 함수일까요?
changeID가 실행되는 시점에 validateID가 판단하는 근거는 input입니다. 이 input이 어떤 값을 가리키고 있는지 확인해보면 될것같아요.
validateID는 "지금 입력의 결과 input에 들어가있는 string 전체"를 validation해야 합니다.

2020-12-02 11:29 UTC, qnbz209 commented on src/components/IDLabel.jsx
> +        this.props.handleID(event.target.value);
참고가 되었습니다!

2020-12-03 05:05 UTC, scvgoe commented on src/components/Form.jsx
> +    handleID(newID) {
handleId 보다는 setId가 좀 더 자연스럽지 않나요..?

2020-12-03 05:41 UTC, ryuina commented on src/components/Form.jsx
> +    handleID(newID) {
+ 추가로 네이밍은 자유지만 다른사람이 코드를 봤을때 **이게 뭘하는 함수구나!** 알 수 있을만한게 좋습니다~

2020-12-19 13:40 UTC, closed without merging