Fix/with router
qnbz209/pogomgom-react pull request #4
Opened 2020-12-12 08:35 UTC by qnbz209

확인해주세요

2020-12-13 12:43 UTC, ryuina commented on package.json
> +    "tsutils": "^3.17.1",
요건 어디서 사용하나요??

2020-12-13 12:46 UTC, ryuina commented on src/App.js
> +            path="/joinform"
url path는 사용자가 에측 가능한 쉬운 단어들이면 좋겠다.
`join` 만 해도 더 간단하고 좋을것같다.

2020-12-13 12:48 UTC, ryuina commented on src/App.js
> +          <Route
switch가 없어도 됐었나요?

2020-12-13 12:49 UTC, ryuina commented on src/App.js
> +          />
```
<Route path="/complete">
    <Complete id={this.state.id} name={this.state.name} />
</Router>
```

2020-12-13 12:54 UTC, ryuina commented on src/App.js
> +                handleState={this.handleState}/>}
changeParentState={this.handleState}
handleAppState={this.handleState}

2020-12-13 12:55 UTC, ryuina commented on src/pages/Form.jsx
> +                    handleState={this.props.handleState}
`handleState={this.props.handleAppState}`

2020-12-13 12:59 UTC, ryuina commented on src/pages/Home.jsx
> +                    </Link>
Link로 쓰는게 맞습니다 👍 

```
<a href="/joinform"><button/></a>
```

2020-12-13 13:00 UTC, ryuina commented
1. `package-lock.json`  -> .gitignore에 추가해서 빼주세요

2020-12-14 05:43 UTC, scvgoe commented
> 1. `package-lock.json`  -> .gitignore에 추가해서 빼주세요

yarn.lock을 쓰고 있는게 아니라면, package-lock은 반드시 포함되어야 합니다.
dependency의 tree 구조에 대한 정보를 담고 있어서,
lock파일이 없으면, 같은 package.json을 보더라도 환경에 따라 tree 구조가 달라지고, 예기치 못한 동작을 유발할 수 있습니다.

2020-12-14 05:56 UTC, ryuina commented
> > 1. `package-lock.json`  -> .gitignore에 추가해서 빼주세요
> 
> yarn.lock을 쓰고 있는게 아니라면, package-lock은 반드시 포함되어야 합니다.
> dependency의 tree 구조에 대한 정보를 담고 있어서,
> lock파일이 없으면, 같은 package.json을 보더라도 환경에 따라 tree 구조가 달라지고, 예기치 못한 동작을 유발할 수 있습니다.
> 
> 그 무섭다는 `제 자리에서는 잘 되는데요?` 를 유발할 가능성이 생깁니다.

@scvgoe 
예전에 일할때는 package-lock.json을 포함하면 버전 conflict이 생긴 경우도 있어서 ignore하라고 가르침 받았던것같은데 케바케인걸까요? 
처음에 그렇게 한 이후로 관습적으로 ignore하며 쓰고있어서요
뭔가 local의 global node package랑 충돌했던것 같기도 하고...

2020-12-14 06:39 UTC, ryuina requested changes
수정사항은 이 PR에 반영하고, approve -> merge 하도록 부탁드립니다~ 
작업 고생 많으셨습니다!

2020-12-14 06:39 UTC, ryuina commented on src/App.js
> +  handleState(key, value) {
"handle" 이라는 naming은 보통 "handler" -> "Event Handler" 같은 데에 씁니다.
물론 naming에 정답은 없지만, handle + state 보단 `changeState`, 혹은 더 자세하게  `setStateWithKey` 같은 네이밍은 어떨까요?

2020-12-14 06:39 UTC, ryuina commented on src/components/AdButton.jsx
> +                                     ? true : ((event.target.value === "false")
`event.target.value`를 2번 이상 쓰는 경우,
상단에서 따로 const로 정의해놓고 쓰는것이 조금이나마 computing을 줄일 수 있습니다.
한 번 `const value = event.target.value` 로 저장해놓으면 
event에서 target을 찾고 target에서 value를 찾고 요 과정을 좀 더 줄일 수 있으니까요.
그리고 코드를 짧게 줄일수도 있습니다

2020-12-14 06:39 UTC, ryuina commented on src/components/ConditionalLink.jsx
> +      : <>{children}</>;
공통으로 쓰는, state가 없는 component를 따로 분리한것에 👍 
그리고 class로 안만들고 functional component로 만든 것에도 👍 점수 드립니다
`children`이 어떤게 넘어오는지, 알고 계시다면,
 왜 `<>{children}</>` 과 같이 `<>` = fragment로 감싸야 했는지 알고 계시다면 좋겠습니다.

2020-12-14 06:39 UTC, ryuina commented on src/components/EmailLabel.jsx
> +        this.validateEmail(event.target.value);
요기도 event.target.value를 공통 사용하는 constant로 분리하면 좋겠습니다

2020-12-14 06:39 UTC, ryuina commented on src/pages/Complete.jsx
> +                    {this.state.date.toLocaleDateString()} {this.state.date.toLocaleTimeString()}에 가입되었어요!
요기도 `this.state.date`를 여러번 쓰죠,
요런 부분도 return 전에 미리 constant로 받아놓는것이 좋습니다.
*불필요한 연산을 줄이자!*

2020-12-14 06:39 UTC, ryuina commented on src/pages/Complete.jsx
> +    }
return 부분은 그 Component의 "view"에 해당합니다.
취향에 따라서 view를 한눈에 보기 위해서 다음과 같이 개발하기도 해요.
view에 최대한 로직을 넣지 않는거죠.

```
render() {
        const { name, id } = this.props;
        const dateString = this.state.date.toLocaleDateString();
        const timeString = this.state.date.toLocaleTimeString();
        // 참고 date - time을 한번에 string으로 보여주는 것도 있을수 있어요.
        return (
            <div>
                <div>
                    가입 감사합니다! {name}님!
                </div>
                <div>
                    {id}로
                    {dateString} {timeString}에 가입되었어요!
                </div> </div>
```

2020-12-14 06:39 UTC, ryuina commented on src/pages/Form.jsx
> +                           this.state.adAgree !== null &&
this의 state를 너무 많이 접근하죠,
요부분은 아래와 같이 한번에 펼쳐서 쓸수도 있습니다.
```
const { isIDValid, isPwdValid, ... } = this.state;
const isAllValid = isIDValid && isPwdValid && ...;
```

2020-12-14 06:43 UTC, scvgoe commented
와 류선생님 진짜 너무 꼼꼼하게 잘 봐주시네요.. 쩐다..

2020-12-14 14:05 UTC, qnbz209 commented
## 작업 내용
- 함수 내에서 중복 사용되는 변수를 constant로 묶는 작업을 진행했습니다
- handleState의 naming을 변경하였습니다
- return() 안에서의 변수 계산을 피하도록 수정하였습니다

## 이슈
- Conditional Link에서 Children이 뜻하는 바가 선언한 Button임을 알겠으나, fragment를 꼭 사용해야 하는 이유에 대해서는 잘 모르겠습니다

2020-12-15 06:09 UTC, ryuina approved these changes
리뷰받지 않은 부분의 네이밍도 고려한 것이 좋았습니다

---

```
<ConditionalLink to="..." condition={...}>
    <JoinButton ... />
</ConditionalLink>
```
코드에서 `<ConditionalLink>` `</ConditonalLink>` 사이에 있는 모든것이 Component의 props.children으로 들어오게 되어있습니다.

`ContionalLink = ({ children }) =>` 에서 children으로는 항상 Component 호출 부분 태그 사이에 있는 것들의 List가 들어옵니다.

```
<ParentComponent>
    <Component1/>
    <Component2/>
    <Component3/>
</ParentComponent>
```
위와 같은 코드에서 ParentComponent가 받는 props.children은 `[Component1, Component2, Component3]`이 됩니다. 
그러므로 children는 복수의 component가 있는 collection이고, 이를 fragment로 감싸는게 맞습니다.
(react component rendering의 결과는 하나로 감싸져야 하기 때문에 - div 혹은 fragment로 감싼다고 얘기했던것 참고)
이렇게 Component에서 children을 내려받아서 그리는 예시는 `<Route><Component/><Route>` 와 비슷하다고 생각하면 됩니다.

2020-12-15 12:03 UTC, merged