fetch를 이용해 외부 API와 통신하는 기능 추가
qnbz209/pogomgom-react pull request #6
Opened 2020-12-29 04:04 UTC by qnbz209

##작업 내용
-fetch를 사용하였습니다
-아이디 중복확인과 서버에 가입 데이터를 전송하도록 하였습니다
##이슈
-Conditional Link를 그대로 사용하다 보니 가입버튼을 누르는 동시에 fetch가 이루어지지만 fetch가 성공한 즉시 성공페이지로 넘어가지 못합니다

2021-01-01 09:57 UTC, ryuina requested changes
작업 고생 많으셨습니다 👍 
fetch를 사용해서 적절히 에러 처리에 성공하셨군요!

한가지 희소식으로 서버에 cors 필터를 추가했으니 클라이언트 쪽에서 cors 처리 없이 바로 데이터 받아올 수 있습니다~!

2021-01-01 09:57 UTC, ryuina commented on src/components/PostData.jsx
> +    var data = await fetch(url, requestOptions).then(function (response) {
지정이 된 이후 변하지 않을 변수에는 `var`보다 `const`로 명시하는게 좋습니다.

2021-01-01 09:57 UTC, ryuina commented on src/components/PostData.jsx
> +    return data;
위 코드는 아래와 같이 줄일 수 있습니다.

```
async function postData(url, requestOptions) {
    return await fetch(...).then(...);
}
```
그리고 fetch가 promise 그 자체이기 때문에, async와 await을 생략해도 됩니다,
가져가서 쓰는 데에서는 어차피 await 해야 하니까요.

```
const postData = (url, reqOptions) => fetch(url, reqOptions).then(res => res.status);
```

2021-01-01 09:57 UTC, ryuina commented on src/pages/Signup.jsx
> +                        validate={this.setStateWithKey} />
JoinButton에서 fetchSuccess를 true로 만들어 줘야만 페이지가 넘어가는 구조라면, 버튼에 ConditionalLink로 감싸는 것 보단, 로button클릭시 처리 함수에서 url을 강제 이동시켜주는 방법이 좋을것 같아요.
react-router의 brouser.history.push("다음 url path") 를 찾아보심이

2021-01-01 09:57 UTC, ryuina commented on src/App.js
> +            <Route path="/success">
적절한 경로에 대한 고민이 보여서 좋네요 👍

2021-01-01 09:57 UTC, ryuina commented on src/components/PostData.jsx
> +    return data;
짧은 코드가 항상 정답은 아니지만, 이렇게 표현할 수 있다는것도 알면 좋아요

2021-01-01 09:57 UTC, ryuina commented on src/components/PostData.jsx
> +export default postData;
자주쓰는 fetch 용법을, 특히 이 함수는 response의 status를 받아오기 위한 공통 function으로 보이는데요,
우선 post method만을 위한 함수로 보이지는 않으니 postData보다는 fetchData,
그리고 response를 통채로 받기보단 status를 추출하는 용도로 보이니 `getFetchStatus` 정도로 네이밍하는것이 좋아보여요.
status만을 받는 함수라, 나중에 response 데이터를 받아서 처리해야할 일이 생기면 함수를 또 만들어야 할 것 같은데 이런 고민도 하면 좋겠습니다.
공통된 로직을 추출해서 모듈화 하는 부분은 칭찬합니다.

추가로, 이런 함수는 Component라 볼 수는 없죠, common이라는 폴더에 넣거나, 아니면 utils.js와 같이 유틸 함수를 한 파일에 몰아서 넣는 방법도 있으니 참고를, 그리고 jsx 확장자도 필요 없어 보입니다.

2021-01-03 08:41 UTC, qnbz209 reviewed
리뷰에 대한 반영이 늦어졌습니다
말씀해주신 수정 사항 중 history.push의 경우 history에 추가만 되고 페이지가 실제로 바뀌지 않는 것처럼 보여 history.forward를 추가해주긴 했습니다만 적절치 않아 보여 재검토 부탁드립니다
그리고 우선 리덕스 연동 기능은 가장 최근 커밋에 맞게 제작할 수 있도록 하겠습니다

2021-01-03 08:42 UTC, qnbz209 commented
리뷰에 대한 반영이 늦어졌습니다
말씀해주신 수정 사항 중 history.push의 경우 history에 추가만 되고 페이지가 실제로 바뀌지 않는 것처럼 보여 history.forward를 추가해주긴 했습니다만 적절치 않아 보여 재검토 부탁드립니다
그리고 우선 리덕스 연동 기능은 가장 최근 커밋에 맞게 제작할 수 있도록 하겠습니다

2021-01-03 11:51 UTC, ryuina requested changes

2021-01-03 11:51 UTC, ryuina commented on src/components/JoinButton.jsx
> +                window.history.replaceState({}, '', "/success");
export default withRouter(JoinButton)으로 하고,
this.props.history -> 요거를 이용하자

2021-01-04 12:29 UTC, qnbz209 commented on src/components/JoinButton.jsx
> +                window.history.replaceState({}, '', "/success");
CORS 우회 방법의 제거와 withRouter 이용하였습니다

2021-01-10 12:13 UTC, ryuina approved these changes
굿 잡

2021-01-10 12:14 UTC, merged