Feature/with redux
qnbz209/pogomgom-react pull request #7
Opened 2021-01-03 09:29 UTC by qnbz209

## 작업 내용
- App 최상단에 있는 state를 redux에 연동하였습니다
## 이슈
- subscribe 미구현

2021-01-10 12:43 UTC, ryuina requested changes

2021-01-10 12:43 UTC, ryuina commented on package.json
> +    "redux-devtools-extension": "^2.13.8",
`redex-devtools-extension` 은 개발모드에서만 사용하는 package, dependency (의존성)이기 때문에 install할때 --dev 같은 option을 붙여주면 센스있는 개발자가 될 수 있겠죠

2021-01-10 12:43 UTC, ryuina commented on src/containers/SignupContainer.jsx
> +            changeParentState = {changeInput} />
각 field에서 change가 있을 때 마다 action이 dispatch 되는데 이렇게 되면 
- 나중에 여러 action이 뒤섞였을 때 디버깅이 어려울 수 있다
- redux state가 진정 필요한 것들 위주로 넣는게 결국 global 저장 공간 안정화 부분에서도 좋을 것 같다.
- redux action이 동시에 너무 많이 호출되면 redux가 과연 안전할까?

2021-01-10 12:43 UTC, ryuina commented on src/components/JoinButton.jsx
> +            const url = 'http://ec2-18-221-142-60.us-east-2.compute.amazonaws.com:3000/signup';
요런 base url은 constant로 만들어서 import해서 쓰는 게 안전하다.
constant 폴더를 만들어도 좋고,,

2021-01-10 13:55 UTC, qnbz209 commented
수정 확인 후 approve 부탁드립니다

2021-01-13 05:50 UTC, ryuina requested changes
constant를 모아두는 파일을 하나 만들어서, 여러개 export할 수 있다면 파일 수를 줄일 수 있을 것 같아요.
constant.js를 만드는 방법도 있고, 사용하는 용도 별로
constant/signup.js, constant/complete.js 등으로  나눠서 쓸 수는 있겠죠.
signup.js에서는 

```
export const SIGNUP_URL = ..;
export const CONST_1 = ...;
```

요렇게요


이부분만 수정되면 approve 하겠습니다~ naming에 대한 고민을 항상 하면서 부분부분 리팩토링하는것이 좋네요 👍

2021-01-13 05:50 UTC, ryuina commented on src/constants/SignupUrl.js
> +const signup_url = 'http://ec2-18-221-142-60.us-east-2.compute.amazonaws.com:3000/';
export해서 쓰는 constant는 보통 대문자 네이밍을 많이 씁니다.
SIGNUP_URL 정도가 좋아보여요
https://github.com/airbnb/javascript#naming--uppercase 참조

2021-01-13 08:33 UTC, scvgoe commented on src/components/JoinButton.jsx
> +            var status = await getFetchStatus(url, this.props.requestOptions);
const..?

2021-01-13 08:34 UTC, scvgoe commented
와 대단해요 👍

2021-01-15 02:22 UTC, qnbz209 commented on src/components/JoinButton.jsx
> +            var status = await getFetchStatus(url, this.props.requestOptions);
코멘트를 확인하고 var, const, let 등의 차이에 대해 조사해보았습니다
해당 내용이 재사용되는 것도 아니기에 선언하는 부분을 삭제해주었습니다

2021-01-16 13:18 UTC, ryuina commented on src/components/JoinButton.jsx
> +            var status = await getFetchStatus(url, this.props.requestOptions);
정말 멋져요~

2021-01-16 13:18 UTC, ryuina commented
conflict 해결해주세요~

2021-01-17 12:55 UTC, ryuina approved these changes
conflict도 해결하느라 아주 수고가 많았습니다 👍

2021-01-18 00:27 UTC, merged