Hook을 이용한 refactoring
qnbz209/pogomgom-react pull request #8
Opened 2021-01-18 03:49 UTC by qnbz209

##작업 내용
-React component를 hook을 이용한 function으로 refactoring

2021-01-19 14:33 UTC, scvgoe commented on src/components/AdButton.jsx
> +    function changeAd(event) {
useCallback과 같은 memoization 함수를 잘 활용해주세요!

2021-01-23 02:21 UTC, qnbz209 commented on src/components/AdButton.jsx
> +    function changeAd(event) {
렌더링 비용 절약을 돕는 memoization 함수의 사용법을 익혔습니다!

2021-01-23 03:03 UTC, scvgoe commented on src/components/AdButton.jsx
> +    function changeAd(event) {
정말 훌륭하군요...!!

2021-01-24 11:10 UTC, ryuina commented on src/components/AdButton.jsx
> +    function changeAd(event) {
멋져

2021-01-24 11:48 UTC, ryuina requested changes
수고 많으셨습니다 짝짝짝

2021-01-24 11:48 UTC, ryuina commented on src/components/EmailLabel.jsx
> +    const { email, setStateWithKey } = props;
```
function EmailLabel({ email, setStateWithKey }) {

}
```

요렇게 줄일 수 있습니다.


```
function addItems(list) {
  return list[0] + addItems(list.subarray(1));
}

function addItems([a, ...sublist]) {
  return a + addItems(sublist);
}
```

2021-01-24 11:48 UTC, ryuina commented on src/components/EmailLabel.jsx
> +                setErrmsg('이메일 양식 맞춰주세요');
ErrorMsg, ErrorMessage, 요렇게 장황하게 써도 됩니다.
20자 까지는 괜찮지 않나...

2021-01-24 11:48 UTC, ryuina commented on src/components/JoinButton.jsx
> +import { useHistory, withRouter } from 'react-router-dom';
withRouter + props.history는 useHistory로 대체되는 것입니다

2021-01-31 03:08 UTC, merged